### ISSUE TITLE
Touch up login and signup pages

### ISSUE THREAD

**Issue by asaf-kali** [asaf-kali/coursist#44]
- Translate everything to Hebrew.
- Add first name last name fields to signup page.
- Solve the bug where signup page redirects outside of the default template.

**Comment by asaf-kali** [comment]
- Translate everything to Hebrew.
 - Add first name last name fields to signup page.
 -Solve the bug where signup page redirects outside of the default template.

**Comment by evyatar100** [comment]
* Solve the bug where signup page redirects outside of the default template.

 - solved

**Comment by evyatar100** [comment]
Translate everything to Hebrew:

I've translated it. but there is a conflict with @avihai-huji 's work

**Comment by evyatar100** [comment]
Add first name last name fields to signup page - I don't agree.

**Comment by evyatar100** [comment]
@asaf-kali   can we close this?

**Comment by asaf-kali** [comment]
Merged #47, #48
