### ISSUE TITLE
Suggestion: add a "year taken" field

### ISSUE THREAD

**Issue by iporat08** [asaf-kali/coursist#59]
Hey!
I think that when a user writes a review about a course he\she should fill an additional filed stating in which year he\she was enrolled in it.
Feels to me like this information is important for the relevance of the review.

BTW, your project looks great!

Ido

**Comment by asaf-kali** [comment]
Great, thanks :)

**Comment by evyatar100** [comment]
@iporat08  Thanks for the advice. added it in #87.

**Comment by asaf-kali** [comment]
Not yet on master
