### ISSUE TITLE
Shnaton parser - update and not just add

### ISSUE THREAD

**Issue by asaf-kali** [asaf-kali/coursist#8]
Right now, the shnaton parser only checks if the parsed object already exist in the database with their exact fields. If some field was changes (let's say an hour of a lesson) the shnaton parser will create a new lesson for that.
We need to be able to tell when a certain object is not new, find out what is the old object, and update it (or delete it and replace with a new one).

**Comment by matanel-oren** [comment]
see https://github.com/asaf-kali/coursist/pull/110
