### ISSUE TITLE
Limit comment length

### ISSUE THREAD

**Issue by asaf-kali** [asaf-kali/coursist#84]
A comment should be straight forward.
Also, this prevents UI issues like that:
![image](https://user-images.githubusercontent.com/28392088/85933113-f40c0b00-b8db-11ea-9808-b7bbaa424552.png)

This includes:
- Limit on the forntend textarea to 350 chars + chacracter counter indicator (easy),
- On the database-level (also easy) limit to 400 chars. Make sure no present comment is longer then 400 chars - if it is, the migration will probably fail/make a mess!

**Comment by evyatar100** [comment]
The current limit is 3000 chars. I'm not sure we should lower this number. If someone wants to elaborate, he/she should be able to do so.

**Comment by asaf-kali** [comment]
Ok, we need to think about it.
