### ISSUE TITLE
Add abilitiy to export Calendar to standard format 

### ISSUE THREAD

**Issue by nvgoldin** [asaf-kali/coursist#94]
It would be great if you could export the calendar to iCal format - this would allow to import it to Google Calendar for example. Later on also support for subscribing to an iCal link can be added.

**Comment by matanel-oren** [comment]
An important issue. Maybe it would be simpler to start from export to PDF, so the the user would be able to store his schedule locally.

**Comment by nvgoldin** [comment]
@matanel-oren I started working on it.. currently implementing it as a backend feature, so you could download the event in `.ics` format. Turned out to be a bit more complex than I thought :)

**Comment by matanel-oren** [comment]
I didn't open a separate issue for downloading as PDF, so please don't close this issue before it is done also.

**Comment by nvgoldin** [comment]
@matanel-oren cool, maybe we can combine efforts? see my PR - probably can use the same mechanism (schedule_export.py), would only require doing the conversion to events (i.e. add another method `def as_pdf(...)`)

**Comment by asaf-kali** [comment]
Why is download as pdf needed? After being able to export as `.ics`, it looks redundant, isn't it?

**Comment by nvgoldin** [comment]
@asaf-kali good point, dunno actually. I don't like PDFs :) but maybe people do have a use case for that. I agree its not the ideal format for calendar events.
