### ISSUE TITLE
Bug - When adding courses in the schedule builder with class types 8-17, their background color is not shown in the time table. For example the course 29168 is loaded but without background color because its class type is 16 (Shiur veSeminar).

### ISSUE THREAD

**Issue by carmelLevy** [asaf-kali/coursist#95]
Hi,
I found a bug in your project- When adding courses in the schedule builder with class types 8-17, their background color is not shown in the time table.
For example the course 29168 is loaded but without background color because its class type is 16 (Shiur veSeminar).

**Comment by avihai-huji** [comment]
Thanks for the fix!

**Comment by asaf-kali** [comment]
Merged #96
